# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://github.sora233.me
date_format: "ordinal"
title: 穹妹的小窝
author: Sora233
github_username: sora233

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
  input: GFM
paginate: 9
permalink: /:year/:month/:day/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
collections:
  wiki:
    output: true
    permalink: /wiki/:path
  game:
    output: true
    permalink: /game/:path
exclude: [.idea]


# ---------------- #
#      Comments    #
# ---------------- #
comments_provider: disqus
gitment:
  owner: sora233-001
  repo: sora233-gitment
  oauth:
    client_id: 9cedf4c0d94a87ce8d3c
    client_secret: 125498df2ff2f112598e373738c3e2b91630190c

jekyll_compose:
  default_front_matter:
    drafts:
      categories: 日常
      description:
      keywords:
    posts:
      categories: 日常
      description:
      keywords:
